# Generated by Django 6.1 on 2026-09-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("DELETE", "Delete"),
                    ("APPROVE", "Approve"),
                    ("REJECT", "Reject"),
                    ("SIGN", "Sign"),
                    ("UPLOAD", "Upload"),
                    ("DOWNLOAD", "Download"),
                    ("ASSIGN", "Assign"),
                    ("RENEW", "Renew"),
                    ("VIEW", "View"),
                    ("CANCEL", "Cancel"),
                ],
                max_length=20,
            ),
        ),
    ]
