# Generated by Django 6.1 on 2026-09-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("signatures", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="signature",
            name="signature_image",
        ),
    ]
